### PR TITLE
Fixes #4 allows list of ips to be used

### LINKED ISSUE #4: Allow administration from a list of IPs instead of a single IP
`admin_ip` variable is a string and needs to be a list to allow more than one IP for the `administration` security group.

### PR DESCRIPTION
**Pull request by mikeaorlando**
Multiple admin IPS can be defined.

### CODE REVIEW

**Comment by mikeaorlando** [comment]
fixes #4

**Comment by jonathanleek** [comment]
Documentation?

**Comment by jonathanleek** [comment]
Looks good!

**Review by jonathanleek — APPROVED** [review]
Looks good!

**Pull request merged**
